# Generated by Django 5.0.6 on 2024-06-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('student_no', models.CharField(max_length=32, unique=True)),
                ('student_name', models.CharField(max_length=32)),
            ],
        ),
    ]
